// <auto-generated />
using System;
using EpsSchool.infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EpsSchool.Infra.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EpsSchool.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Informatica"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manutenção de Micros"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Redes de Computadores"
                        });
                });

            modelBuilder.Entity("EpsSchool.Domain.Entities.CourseSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("SubjectId");

                    b.ToTable("CoursesSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            SubjectId = 4
                        });
                });

            modelBuilder.Entity("EpsSchool.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4")
                        .HasMaxLength(120);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4")
                        .HasMaxLength(120);

                    b.Property<int>("Registration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2005, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Joana",
                            PhoneNumber = "33556699",
                            Registration = 1,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 145, DateTimeKind.Local).AddTicks(6664),
                            Status = true,
                            Surname = "Alves"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2005, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fernanda",
                            PhoneNumber = "33447789",
                            Registration = 2,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 145, DateTimeKind.Local).AddTicks(7547),
                            Status = true,
                            Surname = "Silva"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(2005, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vanessa",
                            PhoneNumber = "99562341",
                            Registration = 3,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 145, DateTimeKind.Local).AddTicks(7989),
                            Status = true,
                            Surname = "Lisboa"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(2005, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maria",
                            PhoneNumber = "99452417",
                            Registration = 4,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 145, DateTimeKind.Local).AddTicks(8366),
                            Status = true,
                            Surname = "Madalena"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(2005, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "João",
                            PhoneNumber = "98564712",
                            Registration = 5,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 145, DateTimeKind.Local).AddTicks(8686),
                            Status = true,
                            Surname = "Paulo"
                        },
                        new
                        {
                            Id = 6,
                            Birthdate = new DateTime(2005, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ananias",
                            PhoneNumber = "33589624",
                            Registration = 6,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 145, DateTimeKind.Local).AddTicks(9084),
                            Status = true,
                            Surname = "Fernandes"
                        },
                        new
                        {
                            Id = 7,
                            Birthdate = new DateTime(2005, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "José",
                            PhoneNumber = "98745122",
                            Registration = 7,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 145, DateTimeKind.Local).AddTicks(9399),
                            Status = true,
                            Surname = "Arimatéia"
                        });
                });

            modelBuilder.Entity("EpsSchool.Domain.Entities.StudentCourseSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Grade")
                        .HasColumnType("int")
                        .HasMaxLength(9999);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StudentId", "CourseSubjectId");

                    b.HasIndex("CourseSubjectId");

                    b.ToTable("StudentsCoursesSubjects");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseSubjectId = 1,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(4648)
                        },
                        new
                        {
                            StudentId = 2,
                            CourseSubjectId = 1,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5827)
                        },
                        new
                        {
                            StudentId = 3,
                            CourseSubjectId = 1,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5864)
                        },
                        new
                        {
                            StudentId = 1,
                            CourseSubjectId = 2,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5868)
                        },
                        new
                        {
                            StudentId = 2,
                            CourseSubjectId = 2,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5870)
                        },
                        new
                        {
                            StudentId = 3,
                            CourseSubjectId = 2,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5876)
                        },
                        new
                        {
                            StudentId = 4,
                            CourseSubjectId = 3,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5878)
                        },
                        new
                        {
                            StudentId = 5,
                            CourseSubjectId = 3,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5880)
                        },
                        new
                        {
                            StudentId = 4,
                            CourseSubjectId = 4,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5882)
                        },
                        new
                        {
                            StudentId = 5,
                            CourseSubjectId = 4,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5886)
                        },
                        new
                        {
                            StudentId = 4,
                            CourseSubjectId = 5,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5888)
                        },
                        new
                        {
                            StudentId = 5,
                            CourseSubjectId = 5,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5890)
                        },
                        new
                        {
                            StudentId = 5,
                            CourseSubjectId = 6,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5892)
                        },
                        new
                        {
                            StudentId = 6,
                            CourseSubjectId = 6,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5894)
                        },
                        new
                        {
                            StudentId = 7,
                            CourseSubjectId = 6,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5897)
                        },
                        new
                        {
                            StudentId = 5,
                            CourseSubjectId = 7,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5899)
                        },
                        new
                        {
                            StudentId = 6,
                            CourseSubjectId = 7,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5901)
                        },
                        new
                        {
                            StudentId = 7,
                            CourseSubjectId = 7,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 146, DateTimeKind.Local).AddTicks(5904)
                        });
                });

            modelBuilder.Entity("EpsSchool.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4")
                        .HasMaxLength(120);

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Workload")
                        .HasColumnType("int")
                        .HasMaxLength(9999);

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Matemática",
                            TeacherId = 1,
                            Workload = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Limpeza de Gabinete",
                            TeacherId = 2,
                            Workload = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Português",
                            TeacherId = 3,
                            Workload = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Arquitetura de Servidores",
                            TeacherId = 4,
                            Workload = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Programação",
                            TeacherId = 5,
                            Workload = 0
                        });
                });

            modelBuilder.Entity("EpsSchool.Domain.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4")
                        .HasMaxLength(120);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4")
                        .HasMaxLength(120);

                    b.Property<int>("Registration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(120) CHARACTER SET utf8mb4")
                        .HasMaxLength(120);

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "José",
                            PhoneNumber = "44778899",
                            Registration = 1,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 141, DateTimeKind.Local).AddTicks(2692),
                            Status = true,
                            SubjectId = 0,
                            Surname = "Roberto"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carlos",
                            PhoneNumber = "33568941",
                            Registration = 2,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 142, DateTimeKind.Local).AddTicks(1115),
                            Status = true,
                            SubjectId = 0,
                            Surname = "Eduardo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Manuel",
                            PhoneNumber = "99587462",
                            Registration = 3,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 142, DateTimeKind.Local).AddTicks(1169),
                            Status = true,
                            SubjectId = 0,
                            Surname = "Nobre"
                        },
                        new
                        {
                            Id = 4,
                            Name = "João",
                            PhoneNumber = "33506987",
                            Registration = 4,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 142, DateTimeKind.Local).AddTicks(1173),
                            Status = true,
                            SubjectId = 0,
                            Surname = "Olavo"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lucas",
                            PhoneNumber = "33214896",
                            Registration = 5,
                            StartDate = new DateTime(2021, 4, 2, 17, 38, 2, 142, DateTimeKind.Local).AddTicks(1176),
                            Status = true,
                            SubjectId = 0,
                            Surname = "Ribas"
                        });
                });

            modelBuilder.Entity("EpsSchool.Domain.Entities.CourseSubject", b =>
                {
                    b.HasOne("EpsSchool.Domain.Entities.Course", "Course")
                        .WithMany("CoursesSubjects")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EpsSchool.Domain.Entities.Subject", "Subject")
                        .WithMany("CoursesSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EpsSchool.Domain.Entities.StudentCourseSubject", b =>
                {
                    b.HasOne("EpsSchool.Domain.Entities.CourseSubject", "CourseSubject")
                        .WithMany("StudentsCoursesSubjects")
                        .HasForeignKey("CourseSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EpsSchool.Domain.Entities.Student", "Student")
                        .WithMany("StudentsCoursesSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EpsSchool.Domain.Entities.Subject", b =>
                {
                    b.HasOne("EpsSchool.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
